### ISSUE TITLE
Unable to create testbed.yaml with xlsx file

### ISSUE THREAD

**Issue by yixiuGit** [CiscoTestAutomation/pyats.contrib#21]
I tried to generate testbed.yaml file from xlsx file.
I run the same code on different ubuntu box, both are running 18.4. pyats version is 20.9 on both box as well.
One is ok and the other throw the error as the attachment.
The only difference I can find is the working ubuntu is running xlrd version 1.2, but the other one is running with version 2.0.
Does it related to the below issue?
![error](https://user-images.githubusercontent.com/44864610/105027057-6aa06e00-5aa3-11eb-8dbc-3a4fcd1f855f.jpg)

https://github.com/equinor/fmu-tools/issues/88

**Comment by danielgraziano** [comment]
Hi @yixiuGit, this error is coming from the xlrd package (https://github.com/python-excel/xlrd/) and is not related to pyATS.

Based on the error, the file type `.xlsx` is not supported (https://github.com/python-excel/xlrd/pull/371). Looking at the code, it seems the only supported filetype is `.xls`. You can try with the `.xls` filetype or reach out to the developers of `xlrd` to see if they can add support for `.xlsx`.

**Comment by yixiuGit** [comment]
Hi @danielgraziano , I tested with xls file, it had the same error as the xlsx file.
It only works with csv file.
According to my understanding, xlrd does support xlsx file but need to specify the engine as openpyxl.
Is it possible to define the parameter in your file.py file that allow both xls and xlsx files to work?

**Comment by danielgraziano** [comment]
Hi @yixiuGit, I have updated the install dependencies to use version 1.2 in #22. This is only a temporary fix until we can refactor this feature.

Please install version 1.2 using `pip install xlrd==1.2`
