### ISSUE TITLE
Create NetBox testbed fails with error: "'NoneType' object is not iterable"

### ISSUE THREAD

**Issue by netgab** [CiscoTestAutomation/pyats.contrib#74]
Error is in file [netbox.py](https://github.com/CiscoTestAutomation/pyats.contrib/blob/master/src/pyats/contrib/creators/netbox.py#L147)
The variable `self._verify` is of type `str`. The `requests` module expects a `bool`

Quick fix: 
```
verify=False
```
Or fix it in the class definition

**Comment by sudheergovindu** [comment]
Hi , I am looking at your ticket and reviewing it, Please let me know are you facing the issue still or not ?

**Comment by sudheergovindu** [comment]
please let me know if still facing the issue or not?

**Comment by netgab** [comment]
I'm currently on vacation and don't have access to my pyats / netbox install. As long as nothing has changed on the code base since I opened this issue, it should be still present...

**Comment by sudheergovindu** [comment]
That occurs when you try to iterate over a variable that is None. In Python, None is a special data type that represents the absence of a value.so try with giving value or ensure whether any value is coming or empty values is iterated over.
check and let me know once done after your vacation

**Comment by sudheergovindu** [comment]
verify (bool) default=True: Should requests library validate SSL cert for netbox
 CLI Argument        |  Class Argument
    ---------------------------------------------
    --verify=False      |  verify=False
may i know from where the value false is assigned to self varaible? can you send me the script file from where the input is passing as false.

**Comment by netgab** [comment]
> may i know from where the value false is assigned to self varaible? can you send me the script file from where the input is passing as false.

There is no script file. As I already wrote, I'm just using the CLI:
```
pyats create testbed netbox --output=testbed/netbox.yml --netbox-url=https://192.0.2.1 --user-token=<hidden> --verify=False
```

The `--verify=False` CLI parameter is documented in the [class Netbox(TestbedCreator)](https://github.com/CiscoTestAutomation/pyats.contrib/blob/80cfa10b93fccabbded4204c24475166527bf7e5/src/pyats/contrib/creators/netbox.py#L9) docstring:

So from my point of view it's either a documentation bug in the docstring itself (--verify=False is not supported) or there is a bug in the code base.

The `self.__verify` attribute is somehow inherited from a parent class (maybe `BaseTestbedLoader`).

But anyway ... I guess we are using the incorrect data type for the `requests.get` call..

**Comment by sudheergovindu** [comment]
Certainly, In order to better understand your inquiry and provide further assistance, could you please provide me with more information regarding the response you are receiving in your netbox.py script? This will enable me to better analyze the situation and offer more specific recommendations for any further actions that may be necessary.

**Comment by sudheergovindu** [comment]
please provide me with more information regarding the response you are receiving in your netbox.py script?

**Comment by netgab** [comment]
As written above in my initial post:
```
$ pyats create testbed netbox --output=testbed/netbox.yml --netbox-url=https://192.0.2.1 --user-token=<hidden> --verify=False -vvv
Begin retrieving data from netbox...
The type of self.__verify is: <class 'str'> with value False
Traceback (most recent call last):
  File "src/pyats/cli/base.py", line 207, in pyats.cli.base.Command.main
  File "src/pyats/cli/base.py", line 339, in pyats.cli.base.CommandWithSubcommands.run
  File "src/genie/cli/commands/create_testbed.py", line 34, in genie.cli.commands.create_testbed.CreateTestbed.run
  File "/home/D8ML4I9/aci-testing/venv/lib/python3.9/site-packages/pyats/contrib/creators/creator.py", line 208, in to_testbed_file
    testbed = self._generate()
  File "/home/D8ML4I9/aci-testing/venv/lib/python3.9/site-packages/pyats/contrib/creators/netbox.py", line 589, in _generate
    response += self._get_request(devices_url, headers, "results")
TypeError: 'NoneType' object is not iterable


'NoneType' object is not iterable
```

**Comment by SohanTirpude** [comment]
Hello @netgab,

For the above mentioned problem, PR has been raised and merged. So, kindly check and confirm whether your issue has resolved or not.

**Comment by netgab** [comment]
Hello @SohanTirpude,
thanks you for taking care of the issue. To verify, I need to wait until the new version is published to PyPi. 
Otherwise I need to build the package directly from the sources....

**Comment by SohanTirpude** [comment]
Hello @netgab,

No issue, you can take your time and let me know.

**Comment by SohanTirpude** [comment]
Hello @netgab,

The 23.7 version has been released I guess. So, kindly check and let me know if the issue still persist.

**Comment by netgab** [comment]
Hi @SohanTirpude,
works perfectly now. Thank you!
